# -*- coding: utf-8 -*-
"""simple_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouoLc1zwKn3PbX5E-MR4_XQsHBCDzQhY
"""



"""
Simple CLI Calculator

This Python program is a command-line interface (CLI) calculator that allows users to perform basic arithmetic operations including addition, subtraction, multiplication, and division. The calculator handles user input and executes the appropriate mathematical operation based on the selected operator.

 Features:
- Addition (`+`)
- Subtraction (`-`)
- Multiplication (`*`)
- Division (`/`) with error handling for division by zero.

 How it works:
- The user is prompted to input two numbers and select an operation.

- The program calls the corresponding function (add(), subtract(),multiply (), or divide()) to perform the calculation.

- If the user enters invalid input (e.g., non-numeric values or an invalid operator), the program will display an error message and prompt for valid input.

- After each calculation, the user is asked whether they would like to perform another calculation.

 Error Handling:
- Division by zero is checked and handled gracefully with an error message.
- Invalid input (non-numeric values) is caught and prompts the user to re-enter valid numbers.

This program is simple and user-friendly, making it a handy tool for performing basic arithmetic operations in the terminal.



"""

def add(num1,num2): #adding function
    return num1+num2
def subtract(num1,num2): #subtracting function
    return num1-num2
def multiply(num1,num2): #multipling function
    return num1*num2
def devide(num1,num2): #division function
    if num2 == 0: #checks division by zero
        print ("Division by zero is not allowed.")
        return none
    else:
        return num1/num2

def calc(num1,mun2, op): #this function calls the appropriate function based on the user’s input.
    if op=='+':
        return add(num1,num2)
    elif op=='-':
        return subtract(num1,num2)
    elif op=='*':
        return multiply(num1,num2)
    elif op=='/':
        return devide(num1,num2)
    else:
        print ("Invalid Operator! please enter an opertaor from the list [+,-,*,/]") #if the opration is not from the list the finction prints this message and strats over

print ("Welcome to the Simple CLI Calculator!")

flag="yes"
while(flag=="yes"):
    try:

        num1=float(input("Please enter the first number: ")) #getting the numbers from the user and converting them to float argument
        num2=float(input("Please enter the second number: "))
        op=input("Please choose an operation (+, -, *, /): ") #getting the opertaion from the user
        res=calc(num1,num2,op)
        print("Result: " + str(res)) #printing the result
    except: #if the inputs are not numbers it returns this error message
        print("Invalid input! Please enter numerical values.")

    flag=input("Would you like to perform another calculation? (yes/no): ").lower() #checks if user want to continue

print("Thank you for using the Simple CLI Calculator!")